### ISSUE TITLE
Konfidenzintervalle & Std

### ISSUE THREAD

**Issue by NE4Y** [joeldomke/corona-incidence-tuebingen#2]
Es wäre cool wenn Konfidenzintervalle / Stabdardabweichung mit geplottet werden könnte damit man sieht wie Aussagekräftig die 7-Tagesinzidenz ist.

**Comment by joeldomke** [comment]
Mir ist nicht ganz klar wie man die Werte berechnen soll, hast du irgend ein Beispiel für ne Statistik, wo die Konfidenzintervalle vorhanden sind?

**Comment by joeldomke** [comment]
Ich denk nicht, dass es möglich ist die Werte mit den gegebenen Daten zu berechnen
